import type { Metadata } from "next";
import { Fjalla_One, Poppins } from "next/font/google";
import "./globals.css";
// wagmi
import { WagmiProvider } from "wagmi";
import { config } from "@/config";
// react query-import
import Providers from "./ReactQueryProvider/Providers";

const fjallaOne = Fjalla_One({
  variable: "--fjalla-one",
  subsets: ["latin"],
  weight: ["400"],
});

const poppins = Poppins({
  variable: "--poppins",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fjallaOne.variable} ${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <WagmiProvider config={config}>{children}</WagmiProvider>
        </Providers>
      </body>
    </html>
  );
}
